### ISSUE TITLE
cannot import name dev_appserver

### ISSUE THREAD

**Issue by ronaldocpontes** [django-nonrel/djangoappengine#86]
I am having this problem on a MAC Mountain Lion...

./manage.py runserver

``` python
Traceback (most recent call last):
  File "./manage.py", line 4, in <module>
    import settings # Assumed to be in the same directory.
  File "/Users/ronaldo.pontes/projects/java/py-vm/django-app/settings.py", line 4, in <module>
    from djangoappengine.settings_base import *
  File "/Users/ronaldo.pontes/projects/java/py-vm/django-app/djangoappengine/settings_base.py", line 6, in <module>
    setup_env()
  File "/Users/ronaldo.pontes/projects/java/py-vm/django-app/djangoappengine/boot.py", line 76, in setup_env
    setup_project()
  File "/Users/ronaldo.pontes/projects/java/py-vm/django-app/djangoappengine/boot.py", line 137, in setup_project
    from .utils import have_appserver, on_production_server
  File "/Users/ronaldo.pontes/projects/java/py-vm/django-app/djangoappengine/utils.py", line 20, in <module>
    "Error was: %s" % e)
Exception: Could not get appid. Is your app.yaml file missing? Error was: cannot import name dev_appserver

```

**Comment by jacobg** [comment]
I just noticed on devappserver2, it seems this last update that the local shell does not use the datastore_path option, because my database is empty when using local shell. I have to dig further, but wondering if anyone else also see this?

**Comment by wapcaplet** [comment]
+1 for https://github.com/django-nonrel/djangoappengine/pull/77 - I was getting this error from manage.py:

    Exception: Could not get appid. Is your app.yaml file missing?
    Error was: cannot import name old_dev_appserver

Using the devappserver2 branch fixed it for me, and manage.py works now.
